site_name: Local Lambda Testing Workshop
repo_url: https://github.com/aws-hebrew-book/pytest-lambda-workshop
site_url: http://pytest-lambda-workshop.s3-website-us-west-2.amazonaws.com/
edit_uri: edit/main/docs/
repo_name: pytest-lambda-workshop

theme:
  name: material
  features:
    - content.code.copy
    - header.autohide
    - navigation.footer
    - content.action.edit
  icon:
    logo: material/test-tube
    favicon: images/test-tube.svg
    repo: fontawesome/brands/github
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - social
  - search
extra: 
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/aws-hebrew-book/pytest-lambda-workshop/issues/new/choose" target="_blank" rel="noopener">openning an issue</a>.
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/TServerless
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/efime/

nav:
  - Introduction: 'index.md'
  - Part 1: 
    - Unit Testing and the "Crisis at the Concert": './part1/part1.md'
    - Application Code Overview: './part1/app-description.md'
    - Using pytest: './part1/using-pytest.md'
  - Part 2: 
    - Hello Moto: './part2/part2.md'
    - Writing tests with Moto: './part2/moto-example.md'
  - Part 3: 
    - Using Sam Local: './part3/part3.md'
    - Testing in a real environment: './part3/deploy-to-aws.md'
  - Cleanup: 'cleanup.md'
    