name: Publish to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Set up Poetry
      run: |
        pipx install poetry

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Install dependencies
      run: |
        poetry install
    - name: Build docs
      run: |
        poetry run mkdocs build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::234138278568:role/GitHub-Access
        role-session-name: GitHubActionsSession
    - name: Upload to S3
      run: |
        aws s3 sync --delete ./site s3://pytest-lambda-workshop/
        


